// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAJJsKv0vMMxECkF4TP8hV_B3CjW0kl5I',
    appId: '1:13552027371:web:2c140b9628cf48c839e0ae',
    messagingSenderId: '13552027371',
    projectId: 'sara-6a00c',
    authDomain: 'sara-6a00c.firebaseapp.com',
    storageBucket: 'sara-6a00c.appspot.com',
    measurementId: 'G-H65SSD22FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAwc_r_n42RsebHsdjKU_2zRU04Xij78',
    appId: '1:13552027371:android:33cb1eede14b36ad39e0ae',
    messagingSenderId: '13552027371',
    projectId: 'sara-6a00c',
    storageBucket: 'sara-6a00c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKqFiaxILcUeoT9qj7OmNLmMP4VdjOU98',
    appId: '1:13552027371:ios:bf51c2f3f60deb8b39e0ae',
    messagingSenderId: '13552027371',
    projectId: 'sara-6a00c',
    storageBucket: 'sara-6a00c.appspot.com',
    iosClientId: '13552027371-p033mft9i6o5fj976vjeksoetkrro604.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKqFiaxILcUeoT9qj7OmNLmMP4VdjOU98',
    appId: '1:13552027371:ios:bf51c2f3f60deb8b39e0ae',
    messagingSenderId: '13552027371',
    projectId: 'sara-6a00c',
    storageBucket: 'sara-6a00c.appspot.com',
    iosClientId: '13552027371-p033mft9i6o5fj976vjeksoetkrro604.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
