// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARqXQONpHiapQLluK0vPyOTuDuhDra9UI',
    appId: '1:952455689161:web:04c0b5f1696980160bae18',
    messagingSenderId: '952455689161',
    projectId: 'testapp-394810',
    authDomain: 'testapp-394810.firebaseapp.com',
    storageBucket: 'testapp-394810.appspot.com',
    measurementId: 'G-WHREWHNTJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB07sw8NO6zjvdB0o2UXRPMybxI_4FPW8',
    appId: '1:952455689161:android:77fafe10ef7147810bae18',
    messagingSenderId: '952455689161',
    projectId: 'testapp-394810',
    storageBucket: 'testapp-394810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoIm5e84ej0yjB7wkPwki4GuZroZy4r5c',
    appId: '1:952455689161:ios:09e23eb9cf8d8f8c0bae18',
    messagingSenderId: '952455689161',
    projectId: 'testapp-394810',
    storageBucket: 'testapp-394810.appspot.com',
    iosClientId: '952455689161-5fun6u9f6uli1h50nf7ig4552qhsvb9o.apps.googleusercontent.com',
    iosBundleId: 'com.android.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoIm5e84ej0yjB7wkPwki4GuZroZy4r5c',
    appId: '1:952455689161:ios:3b39556cd0b853f40bae18',
    messagingSenderId: '952455689161',
    projectId: 'testapp-394810',
    storageBucket: 'testapp-394810.appspot.com',
    iosClientId: '952455689161-d4d5nq31ch8m4la09cp5stemv79u6h3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
